### ISSUE TITLE
[Feature🚀] 存储层参考automq的实现

### ISSUE THREAD

**Issue by leyou240** [mxsm/rocketmq-rust#973]
### Is Your Feature Request Related to a Problem?

存储层参考automq的实现 https://github.com/AutoMQ/automq-for-rocketmq和https://github.com/AutoMQ/automq

**Comment by mxsm** [comment]
1

**Comment by mxsm** [comment]
@leyou240 Thanks for your suggestion. The storage implementation will first follow the realization of the RocketMQ Java version. Once the overall progress catches up with the Java version, we will proceed to develop a cloud-native storage solution. This will align with AutoMQ.Since Rust has some syntactical and related differences from the Java version, the overall development is still in the exploratory phase. We've encountered some issues along the way, but we're gradually resolving them.
